= U of C Solar Car Advanced Recruit Training

Intro project to learn C++ and QT

== Running the project

=== Via Command Line

To build this project on Linux navigate to the source directory and run the following commands:

[source,bash]
----
qmake
make
./batteryLife -f myData.csv -i 50
----

Refer to help for further instructions on how to add arguments to the program.
 
You can change the command line arguments within QT Creator with Projects -> Run -> Command Line Arguments.

=== Via QT Creator

In QT Creator, the above `qmake` and `make` are located in `Build`, and the project can be run through the play button. 
You'll have to set the appropriate command line arguments in `Projects > Build & Run > Run`. 

== Objective

The goal of this project is to give new recuits a good starting point to learn the required skills to work on the other projects. 
If you ever need any help with how to use Qt's functions, a good start would be to look at http://doc.qt.io/qt-5.6/reference-overview.html[Qt's reference manual]

=== Tasks to Complete

 *  Complete the error checking in `LogFileReader::parseLine`. 
 The proper format of each line in batData.csv should be hh:mm:ss:zzz, so any other differences should be caught. 
 It should be able to catch all the errors in batDataFailure.csv.
 *  Implement the functions of BatteryStateOfChargeService. 
 See the notes below on how to calculate the values.
 *  Print out the time until depleted or charged (found in BatteryStateOfChargeService) in `BatteryStateDisplayService::handleBatteryDataReceived`.

=== Values to Note for BatteryStateOfChargeService

 *  The battery is charging when the battery current is negative, depleting when it is positive.
 *  The initial amount of Amphours used would be the Battery's Amphour capacity(Ah) multiplied by it's state of charge(%).
 *  The change in amphours used between two data points would be the average current(A) multiplied by the difference in time(h)
 *  The time until charge would be the Amphours used(Ah) divided by the current (A). 
 Similarily, the time until depletion would be the remaining amphours divided by the current.    
