=  Basic Git

== Common Commands

This is just a quick overview of the commands that would be used most frequently:

*  `git add <file>` adds files to the staging area so they can be committed.

*  `git commit -m 'Enter a logical git message'` makes a commit local to your computer with everything that's been "added", i.e. in the staging area.
When writing the commit message, describe what changes are in this commit.
For example if you added a updated a README for clarity, you might use `git commit -m 'Updated the README for clarity`.
Try to be descriptive so that the history is easier to track.

*  `git push` sends your committed changes upstream, in our case to GitHub.

*  `git status` displays the files that have been changed.
Green files means that they have been "added" and are in the staging area.
Red means that they have not been "added".

*  `git pull` pulls down any changes that were done by other people.

*  `git checkout <branchName>` changes branches, add the `-b` flag to move to a new branch.

*  `git push --set-upstream origin <newBranchName>` pushes a new branch from your computer to the 'origin' (Github) for the FIRST time.
All subsequent pushes can just use the `git push` command as listed above.

== Usual Workflow for Making Changes

The usual workflow for pushing changes with Git is as follows.

. Make your changes and save them.
. Use `git add <file>` and add all the files whose changes you want committed.
. Use `git status` to double check what files you've added are in the staging area.
Anything green will be committed.
. Then use `git commit -m 'Your descriptive message'` to commit all the staged changes (green files).
Make sure to write a descriptive commit message!
. Finally use `git push` to push your changes up to Github.

After pushing, your changes should be updated on the Server (Github).

== Further Resources

There are some great Git guides floating around. Check out these:

*  http://rogerdudler.github.io/git-guide/
*  https://git-scm.com/book/en/v2/Getting-Started-Git-Basics
*  https://guides.github.com/
